import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import styles from "./styles/layout.module.css";
import Aside from "@/widgets/layout/Aside";
import Header from "@/widgets/layout/Header";
import TestAPI from "@/widgets/layout/testAPI";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Defines the root layout structure for the application, including global fonts, header, sidebar, main content area, and a test API component.
 *
 * @param children - The main content to be rendered within the layout.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={styles.layout}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <Aside />
        <main className={styles.main}>{children}</main>
        <TestAPI />
      </body>
    </html>
  );
  34;
}
