import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import styles from "./styles/layout.module.css";
import Aside from "@/widgets/layout/Aside";
import Header from "@/widgets/layout/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={styles.layout}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <Aside />
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}
